# Generated by Django 4.2 on 2023-04-11 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short_url',
            fields=[
                ('url', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('unique_url', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(default=datetime.datetime(2023, 4, 11, 14, 9, 15, 661795, tzinfo=datetime.timezone.utc))),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
