# Generated by Django 4.2 on 2023-04-12 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_short_url_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 12, 12, 49, 43, 323482, tzinfo=datetime.timezone.utc)),
        ),
    ]
