# Generated by Django 4.2 on 2023-04-12 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_alter_short_url_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_url',
            name='url',
        ),
        migrations.AlterField(
            model_name='short_url',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 12, 13, 4, 40, 791850, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='unique_url',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='short_url',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
