# Generated by Django 4.2 on 2023-04-12 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_alter_short_url_date_alter_short_url_unique_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 12, 13, 9, 14, 798443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='url',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
